### ISSUE TITLE
Layer size is almost close to 240 MB. Making it unusable as a layer when not using dockerised lambda images

### ISSUE THREAD

**Issue by nabhanh** [sutt0n/serverless-clamav-lambda-layer#5]
Hey, I am not exactly how to tackle this issue but lately the zipped size of the layer tends to reach ~239 MB and when used as a layer with a lambda function gives you the 250 MB size limit exceeded error
```bash
layers › inflating: var/lib/clamav/daily.cvd
layers › inflating: var/lib/clamav/bytecode.cvd
layers › Excluding development dependencies for layer "clamav"
layers › Uploading CloudFormation file to S3
layers › Uploading State file to S3
layers › Uploading service clamav.zip file to S3 (239.9 MB)
```

**Comment by sutt0n** [comment]
This is expected if your Lambda function is large and you're handling somewhat sizeable files to scan; to combat this issue I've created an infrastructure in Terraform here: https://github.com/sutt0n/terraform-fargate-clamav

It's unfortunate, as I had hoped that AWS would increase those size limits, but it makes architectural sense as Lambdas are supposed to be small.

**Comment by sutt0n** [comment]
For further explanation, the reason why it gets so large is because of the ClamAV virus definitions. They come in at over 200MB.

Closing this as it's not an issue pertaining to the lambda layer itself.
